10 PRINT "ENTER A NUMBER AND SEE IF IT'S PRIME"
20 INPUT N
30 IF N<>INT(N) THEN PRINT "ENTER AN INTEGER":GOTO 20
40 IF N<2 THEN PRINT "ENTER AN INTEGER GREATER THAN 1":GOTO 20
50 FOR D=2 TO N-1
60 IF N/D=INT(N/D) THEN PRINT "NOT PRIME, MULTIPLE OF "; D:GOTO 20
70 NEXT D
80 PRINT N; " IS PRIME"
90 GOTO 20